jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pipenv install --dev
      - run: pipenv run black --check .
      - run: pipenv run python -m unittest

version: 2.1
