description: Install dependencies
name: Install
runs:
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
    - run: pip install poetry==1.1.14
      shell: bash
    - run: poetry install
      shell: bash
  using: composite
