jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: ./.github/actions/install
      - run: pipenv run black --check .
      - run: pipenv run pydocstyle

  test:
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: ./.github/actions/install
      - run: pipenv run python -m unittest
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest

on: pull_request
