jobs:
  release:
    container: ghcr.io/elimity-com/insights-client-python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: /root/.local/bin/poetry publish --build

on:
  release:
    types:
      - published
